###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "André",
  "lastName": "Martins",
  "birthday": "1998-07-30"
}

> {% client.global.set("location", response.headers.valuesOf("Location")[0]); %}

###
GET {{location}}